# Generated by Django 4.2.2 on 2023-06-11 13:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='FeedingLocation',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
        migrations.DeleteModel(
            name='Zookeeper',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='exit_date',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.animalhabitat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.positions'),
        ),
        migrations.AlterField(
            model_name='feedingschedule',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.food'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.ticket'),
        ),
    ]
