# Generated by Django 4.2.2 on 2023-06-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0002_food_positions_ticket_delete_feedinglocation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalCategory',
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
    ]
