# Generated by Django 4.2.2 on 2023-06-15 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0005_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='position',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zoo_app.positions'),
            preserve_default=False,
        ),
    ]
